[project]
name = "bills-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arabic-reshaper>=3.0.1",
    "pillow>=12.3.0",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.21.0",
    "pyside6>=6.11.1",
    "python-bidi>=0.6.11",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "deptry>=0.25.1",
]
