[project]
name = "bills-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "html2image>=2.0.7",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pywhatkit>=5.4",
    "requests>=2.34.2",
]
